const sampleCategories = [
  {
    name: 'Necklaces',
    slug: 'necklaces',
    description: 'Majestic chokers, layered rani haars, and contemporary diamond neckpieces crafted to enchant.',
    image: {
      secure_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
      public_id: 'sample_cat_necklaces',
    },
    status: 'active',
  },
  {
    name: 'Rings',
    slug: 'rings',
    description: 'Solitaire engagement rings, intricate polki cocktail bands, and stackable heirloom treasures.',
    image: {
      secure_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
      public_id: 'sample_cat_rings',
    },
    status: 'active',
  },
  {
    name: 'Earrings',
    slug: 'earrings',
    description: 'Cascading jhumkas, chandelier polki drops, and minimalist solitaire diamond studs.',
    image: {
      secure_url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop',
      public_id: 'sample_cat_earrings',
    },
    status: 'active',
  },
  {
    name: 'Bracelets & Bangles',
    slug: 'bracelets-bangles',
    description: 'Hand-engraved temple kadas, flexible diamond tennis bracelets, and jadau bangles.',
    image: {
      secure_url: 'https://images.unsplash.com/photo-1611591475819-79b8b730ab09?q=80&w=1000&auto=format&fit=crop',
      public_id: 'sample_cat_bracelets',
    },
    status: 'active',
  },
  {
    name: 'Pendants',
    slug: 'pendants',
    description: 'Sculptural solitaires and celestial medallions suspended on gossamer gold chains.',
    image: {
      secure_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
      public_id: 'sample_cat_pendants',
    },
    status: 'active',
  },
  {
    name: 'Royal Bridal',
    slug: 'bridal',
    description: 'Magnificent bridal sets, mathapattis, and nath ornaments designed for unforgettable matrimonial grandeur.',
    image: {
      secure_url: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=1000&auto=format&fit=crop',
      public_id: 'sample_cat_bridal',
    },
    status: 'active',
  },
];

const sampleCollections = [
  {
    name: 'Royal Bridal Heritage',
    slug: 'royal-bridal-heritage',
    description: 'An opulent symphony of uncut syndetic Polki diamonds, carved Zambian emeralds, and 22K handcrafted gold.',
    coverImage: {
      secure_url: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=1600&auto=format&fit=crop',
      public_id: 'col_bridal',
    },
    featured: true,
    status: 'active',
  },
  {
    name: 'Celeste Diamond Soliloquy',
    slug: 'celeste-diamond-collection',
    description: 'Precision-cut scintillating solitaire diamonds mounted in platinum and 18K white gold.',
    coverImage: {
      secure_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1600&auto=format&fit=crop',
      public_id: 'col_celeste',
    },
    featured: true,
    status: 'active',
  },
  {
    name: 'The Temple Gold Chronicle',
    slug: 'the-temple-gold-era',
    description: 'Sacred motifs, Nakshi repoussé work, and antique kundan craftsmanship born from Southern Indian dynastic artistry.',
    coverImage: {
      secure_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1600&auto=format&fit=crop',
      public_id: 'col_temple',
    },
    featured: true,
    status: 'active',
  },
  {
    name: 'Everyday Modern Minimalist',
    slug: 'everyday-elegance',
    description: 'Whisper-light diamond pendants, stackable gold bands, and refined tennis silhouettes for daily poise.',
    coverImage: {
      secure_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1600&auto=format&fit=crop',
      public_id: 'col_everyday',
    },
    featured: true,
    status: 'active',
  },
];

const sampleProducts = [
  {
    name: 'Aarohi Royal Polki Choker Suite',
    slug: 'aarohi-royal-polki-choker-suite',
    sku: 'VY-NK-001',
    categorySlug: 'necklaces',
    collectionSlug: 'royal-bridal-heritage',
    shortDescription: 'Uncut syndicate polki diamonds set in 22K hallmarked gold with natural Basra pearl drops.',
    description: 'The Aarohi Choker Suite represents the pinnacle of Rajasthani Meenakari and Jadau art. Handcrafted over 320 hours by our master artisans, this regal collar features hand-selected uncut diamonds set in foil-backed 22 karat yellow gold. It is bordered by natural micro Basra seed pearls and teardrop Zambian emerald beads.',
    price: 385000,
    salePrice: 355000,
    material: '22K Hallmarked Yellow Gold',
    weight: '78.4g Net Gold',
    size: 'Adjustable Silk Dori (14 - 18 inches)',
    stock: 3,
    featured: true,
    newArrival: true,
    bestseller: true,
    rating: 5.0,
    numReviews: 12,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p1_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p1_g1' },
      { secure_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p1_g2' },
    ],
  },
  {
    name: 'Celeste Solitaire Emerald-Cut Diamond Ring',
    slug: 'celeste-solitaire-emerald-cut-diamond-ring',
    sku: 'VY-RG-002',
    categorySlug: 'rings',
    collectionSlug: 'celeste-diamond-collection',
    shortDescription: 'GIA-certified 2.50 Carat Emerald-Cut diamond mounted in Platinum 950 with tapered baguette accents.',
    description: 'An architectural tribute to timeless romance. The Celeste Solitaire features a hand-selected 2.50ct Emerald Cut Diamond of VVS1 clarity and E color grade, embraced by twin tapered baguette diamonds. The band is hand-forged in mirror-polished Platinum 950 with micro-pavé inner gallery detailing.',
    price: 520000,
    salePrice: null,
    material: 'Platinum 950 & 18K White Gold',
    weight: '6.8g Platinum',
    size: 'US 6.5 (Complimentary Resizing)',
    stock: 5,
    featured: true,
    newArrival: false,
    bestseller: true,
    rating: 4.9,
    numReviews: 18,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p2_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p2_g1' },
      { secure_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p2_g2' },
    ],
  },
  {
    name: 'Meera Royal Basra Pearl Jhumkas',
    slug: 'meera-royal-basra-pearl-jhumkas',
    sku: 'VY-ER-003',
    categorySlug: 'earrings',
    collectionSlug: 'royal-bridal-heritage',
    shortDescription: 'Antique kundan work bell earrings accented with natural seed pearls and ruby cabochons.',
    description: 'Echoing the grand courts of Jaipur, the Meera Jhumkas feature tiered filigree bells crowned with floral polki studs. Suspended beneath are cascades of miniature freshwater seed pearls that dance with every gentle movement. Finished with artisanal green enamel on the reverse side.',
    price: 165000,
    salePrice: 148000,
    material: '22K Antique Hallmarked Gold',
    weight: '34.2g Net Gold',
    size: 'Length: 6.5 cm, Width: 3.0 cm',
    stock: 8,
    featured: true,
    newArrival: true,
    bestseller: false,
    rating: 5.0,
    numReviews: 9,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p3_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p3_g1' },
    ],
  },
  {
    name: 'Zaveri Nakshi Temple Kada Bangles',
    slug: 'zaveri-nakshi-temple-kada-bangles',
    sku: 'VY-BG-004',
    categorySlug: 'bracelets-bangles',
    collectionSlug: 'the-temple-gold-era',
    shortDescription: 'Hand-repoussé 22K temple bangles portraying Lakshmi motifs with screw clasp closures.',
    description: 'Handcrafted utilizing the ancient Nakshi repoussé technique where sheets of solid 22K gold are painstakingly hammered and chiseled from within. These ceremonial kadas portray Goddess Lakshmi surrounded by sacred peacocks and floral vines, finished with antique red patina polish.',
    price: 295000,
    salePrice: 280000,
    material: '22K Solid Yellow Gold',
    weight: '52.6g (Pair)',
    size: '2.6 Size (Internal Diameter 60mm)',
    stock: 4,
    featured: false,
    newArrival: false,
    bestseller: true,
    rating: 4.8,
    numReviews: 14,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1611591475819-79b8b730ab09?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p4_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p4_g1' },
    ],
  },
  {
    name: 'Noor Diamond Solitaire Medallion Pendant',
    slug: 'noor-diamond-solitaire-medallion-pendant',
    sku: 'VY-PD-005',
    categorySlug: 'pendants',
    collectionSlug: 'everyday-elegance',
    shortDescription: 'Brilliant round diamond halo set in 18K rose gold with an adjustable Italian chain.',
    description: 'Minimalist luxury designed for daily indulgence. The Noor Medallion suspends a 0.85ct brilliant cut center diamond encompassed by a micro-pavé starburst halo in warm 18 karat rose gold. Includes a 16-18 inch adjustable diamond-cut cable chain.',
    price: 98000,
    salePrice: 89000,
    material: '18K Rose Gold',
    weight: '4.9g',
    size: 'Pendant diameter: 12 mm; Chain: 18 inch',
    stock: 12,
    featured: false,
    newArrival: true,
    bestseller: true,
    rating: 4.9,
    numReviews: 22,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p5_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p5_g1' },
    ],
  },
  {
    name: 'Sultana Navratna Regal Haar',
    slug: 'sultana-navratna-regal-haar',
    sku: 'VY-NK-006',
    categorySlug: 'necklaces',
    collectionSlug: 'royal-bridal-heritage',
    shortDescription: 'Nine astrological royal gemstones hand-set in 22K gold with Colombian emerald tassels.',
    description: 'The Navratna jewel tradition unites the celestial energies of nine auspicious gemstones: Ruby, Natural Pearl, Red Coral, Emerald, Yellow Sapphire, Diamond, Blue Sapphire, Hessonite, and Cat’s Eye. Strung along double-strand Basra pearls with a hand-enamelled royal peacock pendant.',
    price: 460000,
    salePrice: null,
    material: '22K Hallmarked Gold & 9 Certified Gems',
    weight: '92.1g Net Gold',
    size: 'Length: 22 inches',
    stock: 2,
    featured: true,
    newArrival: false,
    bestseller: false,
    rating: 5.0,
    numReviews: 7,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p6_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p6_g1' },
    ],
  },
  {
    name: 'Tara Diamond Eternity Pavé Band',
    slug: 'tara-diamond-eternity-pave-band',
    sku: 'VY-RG-007',
    categorySlug: 'rings',
    collectionSlug: 'everyday-elegance',
    shortDescription: 'Continuous loop of round brilliant-cut diamonds channel-set in 18K yellow gold.',
    description: 'The Tara Eternity Band symbolizes an unbroken circle of grace. Featuring 2.10 total carats of high-fire VS-clarity round brilliant diamonds meticulously prong-set into a sculpted 18K yellow gold band. Sleek, comfortable, and perfect for stacking or as a standalone wedding band.',
    price: 135000,
    salePrice: 125000,
    material: '18K Yellow Gold',
    weight: '5.2g',
    size: 'US 6.0',
    stock: 9,
    featured: false,
    newArrival: true,
    bestseller: true,
    rating: 4.9,
    numReviews: 15,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p7_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p7_g1' },
    ],
  },
  {
    name: 'Kashmiri Chandbali Heritage Drops',
    slug: 'kashmiri-chandbali-heritage-drops',
    sku: 'VY-ER-008',
    categorySlug: 'earrings',
    collectionSlug: 'royal-bridal-heritage',
    shortDescription: 'Crescent moon polki chandbalis with natural emerald cabochons and freshwater pearls.',
    description: 'Crafted in the classical Chandbali crescent silhouette, these ceremonial earrings showcase uncut polki diamonds set in 22K gold foil frames. Suspended from the lower crescent are baroque seed pearls and vivid emerald beads that brush gently against the neck.',
    price: 185000,
    salePrice: 172000,
    material: '22K Hallmarked Gold',
    weight: '38.5g Net Gold',
    size: 'Length: 7.2 cm, Width: 4.0 cm',
    stock: 6,
    featured: true,
    newArrival: false,
    bestseller: true,
    rating: 5.0,
    numReviews: 11,
    mainImage: {
      secure_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1200&auto=format&fit=crop',
      public_id: 'sample_p8_main',
    },
    galleryImages: [
      { secure_url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1200&auto=format&fit=crop', public_id: 'sample_p8_g1' },
    ],
  },
];

module.exports = {
  sampleCategories,
  sampleCollections,
  sampleProducts,
};
